name: Cypress CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Create secure fixture file
        run: |
          mkdir -p cypress/fixtures
          echo "{
            \"firstName\": \"${{ secrets.FIRST_NAME }}\",
            \"email\": \"${{ secrets.EMAIL }}\",
            \"phone\": \"${{ secrets.PHONE }}\",
            \"address\": {
              \"street\": \"${{ secrets.STREET }}\",
              \"city\": \"${{ secrets.CITY }}\",
              \"state\": \"${{ secrets.STATE }}\",
              \"zipCode\": \"${{ secrets.ZIP_CODE }}\"
            },
            \"country\": \"${{ secrets.COUNTRY }}\",
            \"paymentDetails\": {
              \"cardHolderName\": \"${{ secrets.CARD_HOLDER_NAME }}\",
              \"cardNumber\": \"${{ secrets.CARD_NUMBER }}\",
              \"expirationDate\": \"${{ secrets.CARD_EXPIRY }}\",
              \"cvv\": \"${{ secrets.CARD_CVV }}\"
            }
          }" > cypress/fixtures/data.json

      - name: Run Cypress tests in parallel
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          browser: chrome
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

    #   - name: Upload Cypress screenshots
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: cypress-screenshots
    #       path: cypress/screenshots

    #   - name: Upload Mochawesome HTML report
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: mochawesome-report
    #       path: cypress/reports/mochawesome
